title: Cheng Peng's Homepage
page-top-title: Cheng Peng
top-section-bg-text: Computer Science&Economics
home-subtitle: Cheng Peng&ensp;|&ensp;彭诚
copyright-text: '&copy; Cheng Peng 2023-2024. All Rights Reserved.'
