'use strict';
/* All model strings are inserted with textContent. The only innerHTML is our own allowlisted SVG. */
window.mountLesson=function(root,lesson){
const A=window.CottonArt;let step=-1,attempts={},results={},hint=0,solved=false,sequence=[],chosen=null,pairs=new Set(),seen=new Set(),shuffled=[],soundOn=false,toastTimer;
const music=window.GardenSound?new window.GardenSound():null;
const N=(tag,cls='',text)=>{const n=document.createElement(tag);n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const B=(label,fn,cls='secondary')=>{const b=N('button',cls,label);b.type='button';b.addEventListener('click',()=>{if(!b.disabled&&b.isConnected)fn(b);});return b;};
const book='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 180"><path d="M20 145V41Q54 25 80 48Q106 25 140 41V145Q104 130 80 152Q56 130 20 145Z" fill="#f9f1d8" stroke="#748653" stroke-width="3" stroke-linejoin="round"/><path d="M80 48V152M33 62Q54 54 67 63M33 82Q54 74 66 83M96 63Q111 54 126 61M96 84Q111 75 126 82" fill="none" stroke="#aaba86" stroke-width="3" stroke-linecap="round"/><path d="M77 30Q82 6 105 9Q103 32 77 30" fill="#a6bc79" stroke="#748653" stroke-width="2"/></svg>';
const art=(key,cls='')=>{const n=N('div','art '+cls);n.setAttribute('aria-hidden','true');n.innerHTML=key==='book'||!A?.[key]?book:A[key](key==='cotton'&&step>=lesson.stages.length);return n;};
const shuffle=a=>{let b=a.slice();for(let i=b.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}if(b.length>1&&b.every((x,i)=>x===a[i]))b.reverse();return b;};
function toast(t){document.querySelector('.toast')?.remove();clearTimeout(toastTimer);const n=N('div','toast',t);n.setAttribute('role','status');document.body.append(n);toastTimer=setTimeout(()=>n.remove(),4500);}
function modal(title,build){window.speechSynthesis?.cancel();const d=N('dialog','modal'),head=N('div','modal-head');head.append(N('h2','',title),B('关闭',()=>d.close(),'tool'));d.append(head);build(d);document.body.append(d);d.addEventListener('close',()=>d.remove());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.showModal();}
function readSource(id){const source=lesson.sources.find(x=>x.id===id);if(source)modal('回到课文',d=>d.append(N('p','',source.text)));}
function listen(text){const voice=window.speechSynthesis?.getVoices().find(v=>v.localService&&/^zh[-_]/i.test(v.lang));if(!voice)return toast('这台设备没有本地中文声音，请老师或同伴读。');window.speechSynthesis.cancel();music?.stop();const u=new SpeechSynthesisUtterance(text);u.voice=voice;u.lang=voice.lang;u.rate=.88;u.onend=()=>{if(soundOn)music?.start().catch(()=>{});};u.onerror=()=>toast('点读暂不可用，可以继续读文字。');window.speechSynthesis.speak(u);}
function go(n){window.speechSynthesis?.cancel();step=n;hint=0;solved=false;sequence=[];chosen=null;pairs=new Set();seen=new Set();const s=lesson.stages[step];shuffled=shuffle(s?.kind==='order'?s.items.map((_,i)=>i):s?.kind==='match'?s.pairs.map((_,i)=>i):[]);render();window.scrollTo(0,0);root.querySelector('h1,h2')?.focus({preventScroll:true});}
function done(){solved=true;results[step]={completed:true,hints:hint,tries:attempts[step]||0,oral:lesson.stages[step].kind==='speak',exploration:lesson.stages[step].kind==='discover'};if(soundOn)music?.good();render();}
function wrong(){attempts[step]=(attempts[step]||0)+1;hint=Math.min(hint+1,lesson.stages[step].hints.length);render();}
function teacher(){modal('教师入口',d=>{d.append(N('p','','这是教学参考，内容会显示在当前屏幕。'));d.append(B('打开教师参考',()=>{d.close();modal('本课教学参考',box=>{const body=N('div','teacher-copy');body.append(N('p','',lesson.teacherNote||'请结合本班情况核对任务和表达要求。'),N('p','',lesson.approved?'已由导出者勾选核对；不代表教学效果已验证。':'AI／示例草稿，请先核对原文、答案和课堂适配。'),N('p','','下列记录仅对应本设备操作。一名学生答对，不等于全班掌握；口头活动不自动判分。'));lesson.stages.forEach((s,i)=>{body.append(N('h3','',`${i+1}. ${s.goal}`),N('p','',s.teacher));let ans=s.kind==='choice'||s.kind==='evidence'?s.options[s.answer]:s.kind==='order'?s.items.join(' → '):s.kind==='match'?s.pairs.map(p=>p.left+'—'+p.right).join('；'):s.kind==='speak'?'开放表达，请根据实际回答观察。':'探索活动，不代表知识掌握。';body.append(N('p','','参考：'+ans),N('blockquote','',s.quote));const r=results[i];body.append(N('p','',r?r.oral?'本机：已开展表达，未自动评分。':r.exploration?'本机：已查看线索。':`本机：已完成；使用提示 ${r.hints} 次；错误尝试 ${r.tries} 次。`:'本机：尚无完成记录。'));});box.append(body);});},'primary'));});}
function render(){root.replaceChildren();const host=N('div','game theme-'+lesson.theme);root.append(host);const bar=N('header','gamebar'),tools=N('div','gametools');bar.append(N('div','gamebrand',lesson.title));if(step>=0&&step<lesson.stages.length){const p=N('div','gprogress');p.setAttribute('aria-label',`第 ${step+1} 个任务，共 ${lesson.stages.length} 个`);lesson.stages.forEach((_,i)=>p.append(N('span',i<step?'done':i===step?'active':'')));tools.append(p);}const sb=B(soundOn?'静音':'音乐',async()=>{soundOn=!soundOn;try{if(soundOn)await music?.start();else music?.stop();}catch{soundOn=false;toast('音乐暂不可用，游戏可以继续。');}render();},'tool');sb.setAttribute('aria-pressed',String(soundOn));tools.append(sb,B('教师',teacher,'tool'));bar.append(tools);host.append(bar);const main=N('main');host.append(main);if(step<0)return cover(main);if(step>=lesson.stages.length)return end(main);stage(main);}
function heading(host,text){const h=N('h2','',text);h.tabIndex=-1;host.append(h);}
function cover(host){const spread=N('div','gcover'),copy=N('div'),h=N('h1','',lesson.title);h.tabIndex=-1;copy.append(h,N('p','',lesson.subtitle||'一起读一读，找一找。'),B('出发吧',()=>go(0),'primary'));const scene=N('div','scene');scene.append(N('span','sun'),art(lesson.mascot,'scene-art'));spread.append(copy,scene);host.append(spread);}
function end(host){const e=N('div','ending');e.append(art(lesson.mascot),N('h1','','这次冒险，完成啦。'),N('p','','把你发现的事，讲给朋友听。'));const row=N('div','dock');row.append(B('再玩一次',()=>{attempts={};results={};go(-1);},'secondary'),B('教师回顾',teacher,'text-action'));e.append(row);host.append(e);}
function stage(host){const s=lesson.stages[step];heading(host,s.prompt);const card=N('section','card '+s.kind),label=N('div','reading-label');label.append(art(s.art,'portrait'),N('span','','课文里的线索'));card.append(label);host.append(card);
if(!['evidence','discover'].includes(s.kind))card.append(N('p','quote',s.quote));
if(s.kind==='choice'||s.kind==='evidence'){const choices=N('div','choices');s.options.forEach((t,i)=>{const b=B('',()=>i===s.answer?done():wrong(),'choice'+(solved&&i===s.answer?' selected':''));if(s.kind==='evidence')b.append(N('span','num',String(i+1)));b.append(N('span','',t));b.disabled=solved;choices.append(b);});card.append(choices);}
if(s.kind==='order'){const grid=N('div','story-grid');for(const i of shuffled){const pos=sequence.indexOf(i),b=B('',()=>{if(pos<0)sequence.push(i);else sequence.splice(pos,1);render();},'choice'+(pos>=0?' selected':''));b.append(N('span','num',pos>=0?String(pos+1):'·'),N('span','',s.items[i]));b.disabled=solved;grid.append(b);}card.append(grid);}
if(s.kind==='match'){const grid=N('div','match-grid'),left=N('div','match-column'),right=N('div','match-column');s.pairs.forEach((p,i)=>{const b=B(p.left,()=>{chosen=i;render();},'choice'+(pairs.has(i)?' paired':chosen===i?' selected':''));b.disabled=pairs.has(i)||solved;left.append(b);});shuffled.forEach(i=>{const b=B(s.pairs[i].right,()=>{if(chosen===null)return toast('先选左边，再找右边的朋友。');if(chosen!==i){chosen=null;wrong();return;}pairs.add(i);chosen=null;if(pairs.size===s.pairs.length)done();else render();},'choice'+(pairs.has(i)?' paired':''));b.disabled=pairs.has(i)||solved;right.append(b);});grid.append(left,right);card.append(grid);}
if(s.kind==='speak'){const words=N('div','keywords');s.keywords.forEach(t=>words.append(N('span','keyword',t)));card.append(words);}
if(s.kind==='discover'){const grid=N('div','discover-grid');s.cards.forEach((c,i)=>{const b=B('',()=>{seen.add(i);modal(c.label,d=>{d.append(N('p','',c.quote));d.append(B('回到课文',()=>{d.close();readSource(c.sourceId);},'text-action'));});if(seen.size===s.cards.length)done();else render();},'discover');b.append(art(c.art),N('span','',c.label));if(seen.has(i))b.append(N('span','found','✓'));grid.append(b);});card.append(grid);}
if(hint&&!solved){const box=N('div','hint',s.hints[Math.min(hint-1,s.hints.length-1)]||'再回到课文读一读。');box.setAttribute('role','status');card.append(box);}
if(solved){const text=s.kind==='speak'?'和朋友交换一下你们的发现吧。':s.kind==='discover'?'线索找齐了，接着看看吧。':s.feedback||'找到啦，带着发现继续走。';const f=N('p','feedback',text);f.setAttribute('role','status');card.append(f);}
const dock=N('div','dock');if(!solved){dock.append(B('帮帮我',()=>{hint=Math.min(hint+1,Math.max(1,s.hints.length));render();},'text-action left'),B('回到课文',()=>readSource(s.sourceId),'text-action'),B('听一听',()=>listen(s.quote),'text-action'));if(s.kind==='order'){const check=B('排好啦',()=>{if(sequence.every((v,i)=>v===i))done();else{sequence=[];wrong();}},'primary');check.disabled=sequence.length!==s.items.length;dock.append(check);}if(s.kind==='speak')dock.append(B('我说好了',done,'primary'));}else dock.append(B(step===lesson.stages.length-1?'完成冒险':'接着走',()=>go(step+1),'primary'));host.append(dock);}
document.addEventListener('visibilitychange',()=>{if(document.hidden){music?.stop();window.speechSynthesis?.cancel();}else if(soundOn)music?.start().catch(()=>{});});render();
};
